version: "3.7"

services:
  sxb-integration:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - sxb-db
    environment:
      Db:Connection: "Server=sxb-db;Database=sxb;User Id=SA;Password=Develop@90"
      Domain:sXb-frontend: "Just Doesn't need to be empty"
  sxb-db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Develop@90
    expose:
      - "1443"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
