version: 2.1

aliases:
  - &restore_npm_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v1-front-{{ checksum "package.json" }}
        - v1-front-
  - &install_npm
    run:
      name: Install NPM Packages
      command: npm install
  - &restore_dotnet_cache
    restore_cache:
      name: Restore nuget cache
      keys:
        - v1-back-dependencies-{{ checksum "sXb-service/sXb-service.csproj" }}-{{ checksum "sXb-tests/sXb-tests.csproj" }}-{{checksum "sXb-integration-tests/sXb-integration-tests.csproj"}}
        - v1-back-dependencies-
  - &install_nuget
    run:
      name: Install nuget packages
      command: dotnet restore
  - &login_docker
    run:
      name: Login with Docker Account
      command: docker login -u $DOCKER_USER -p $DOCKER_PASS

executors:
  front-exec:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo
  back-exec:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    working_directory: ~/repo
  # Used for running docker commands
  docker-exec:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo

jobs:
  setup-front:
    executor: front-exec
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - *restore_npm_cache
      - *install_npm
      - save_cache:
          name: Cache node_modules
          paths:
            - node_modules
          key: v1-front-{{ checksum "package.json" }}

  flow:
    executor: front-exec
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - *restore_npm_cache
      - *install_npm
      - run: npm run flow

  test-front:
    executor: front-exec
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - *restore_npm_cache
      - *install_npm
      - run: npm test

  setup-back:
    executor: back-exec
    working_directory: ~/repo/backend
    steps:
      - checkout:
          path: ~/repo
      - *restore_dotnet_cache
      - *install_nuget
      - save_cache:
          name: Save dotnet cache
          paths:
            - ~/.nuget/packages
          key: v1-back-dependencies-{{ checksum "sXb-service/sXb-service.csproj" }}-{{ checksum "sXb-tests/sXb-tests.csproj" }}-{{checksum "sXb-integration-tests/sXb-integration-tests.csproj"}}

  test-back:
    executor: back-exec
    working_directory: ~/repo/backend
    steps:
      - checkout:
          path: ~/repo
      - *restore_dotnet_cache
      - *install_nuget
      - run: dotnet test sXb-tests/

  deploy-back:
    executor: docker-exec
    working_directory: ~/repo/backend/
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/repo
      - *login_docker
      - run:
          name: Building Docker Image
          command: docker build -t $DOCKER_USER/sxb-service:$CIRCLE_BRANCH sXb-service/
      - run:
          name: Pushing Image to Docker Hub
          command: docker push $DOCKER_USER/sxb-service:$CIRCLE_BRANCH

  test-integration:
    executor: docker-exec
    working_directory: ~/repo/
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/repo
      - run:
          name: Run Integration Tests
          command: >
            docker-compose -f docker-compose.Test.yml run
            -e Google__Apikey=$Google__Apikey -e Google__Uri=$Google__Uri
            -e SMTP__host=$SMTP__host -e SMTP__password=$SMTP__password
            -e SMTP__sendAddress=$SMTP__sendAddress -e SMTP__port=$SMTP__port
            -e SMTP__username=$SMTP__username -e Cors__FrontendDomain=$Cors__FrontendDomain
            sxb-integration

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - setup-front
      - setup-back
      - flow:
          requires:
            - setup-front
      - test-front:
          requires:
            - setup-front
      - test-back:
          requires:
            - setup-back
      - test-integration:
          requires:
            - setup-back
      - deploy-back:
          requires:
            - test-back
            - test-integration
          filters:
            branches:
              only: master
